name: Build Python APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleDebug --stacktrace

      - name: Find APK
        run: |
          echo "Searching for APK..."
          find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Python-APK
          path: |
            **/build/outputs/apk/**/*.apk
          if-no-files-found: error
